[package]
name = "rock_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rock_core = { path = "../rock_core" }
anyhow = "1.0.66"
log = "0.4.17"